# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'hdo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hdo

    pod 'RealmSwift'
    pod 'Alamofire'
    pod 'AlamofireObjectMapper'
    pod 'Toast'
    pod 'ProgressHUD'

  target 'hdoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hdoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
